feeter/config/routes.rb
Rails.application.routes.draw do

  resources :categories do
    get "new_usuario_category", :on => :collection
  end
  resources :noticias
  resources :usuario_seguidores
  resources :tweets
  resources :usuarios do
    get :lista_de_tweets, :on => :member
  end

  root 'noticias#index'

end

feeter/app/models/usuario.rb
class Usuario < ActiveRecord::Base
  has_many :segue,
            :class_name => "UsuarioSeguidor",
            :foreign_key => :seguidor_id

  has_many :usuarios_seguidos,
            :through => :segue,
            :source => :seguido

  has_many :timeline,
            :through => :usuarios_seguidos,
            :source => :tweets

  has_many :tweets

  validates_presence_of :nome
end

feeter/app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :set_usuario, only: [:lista_de_tweets, :show, :edit, :update, :destroy]

  def lista_de_tweets
    expires_now
  end

  # GET /usuarios
  # GET /usuarios.json
  def index
    @usuarios = Usuario.all
  end

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
  end

  # GET /usuarios/1/edit
  def edit
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to @usuario, notice: 'Usuario was successfully created.' }
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :new }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios/1
  # PATCH/PUT /usuarios/1.json
  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to @usuario, notice: 'Usuario was successfully updated.' }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario.destroy
    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: 'Usuario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def usuario_params
      params.require(:usuario).permit(:nome)
    end
end

feeter/app/helpers/usuarios_helper.rb
module UsuariosHelper
end

feeter/app/views/usuarios/_form.html.erb
<%= form_for(@usuario) do |f| %>
  <% if @usuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

      <ul>
      <% @usuario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

feeter/app/views/usuarios/_tweets.html.erb
<p>
  <h2>Tweets Timeline</h2>
  <% @usuario.timeline.includes(:usuario).each do |tweet| %>
    <%= render tweet %>
  <% end %>
</p>

feeter/app/views/usuarios/edit.html.erb
<h1>Editing Usuario</h1>

<%= render 'form' %>

<%= link_to 'Show', @usuario %> |
<%= link_to 'Back', usuarios_path %>

feeter/app/views/usuarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Usuarios</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Nome</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @usuarios.each do |usuario| %>
      <tr>
        <td><%= usuario.nome %></td>
        <td><%= link_to icon("search"), usuario %></td>
        <td><%= link_to icon("edit"), edit_usuario_path(usuario) %></td>
        <td><%= link_to icon("remove"), usuario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Usuario', new_usuario_path %>

feeter/app/views/usuarios/lista_de_tweets.js.erb
$("#tweets-container").html("<%= escape_javascript (render "tweets") %>")

feeter/app/views/usuarios/new.html.erb
<h1>New Usuario</h1>

<%= render 'form' %>

<%= link_to 'Back', usuarios_path %>

feeter/app/views/usuarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @usuario.nome %>
</p>

<%= link_to "Listar Tweets", lista_de_tweets_usuario_path(@usuario), :remote => true %>

<div id="tweets-container">

</div>

<%= link_to 'Edit', edit_usuario_path(@usuario) %> |
<%= link_to 'Back', usuarios_path %>