feeter/config/routes.rb
Rails.application.routes.draw do

  resources :categories do
    get "new_usuario_category", :on => :collection
  end
  resources :noticias
  resources :usuario_seguidores
  resources :tweets
  resources :usuarios do
    get :lista_de_tweets, :on => :member
  end

  root 'noticias#index'

end

feeter/app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :usuario
end

feeter/app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:texto, :usuario_id)
    end
end

feeter/app/helpers/tweets_helper.rb
module TweetsHelper
end

feeter/app/views/tweets/_form.html.erb
<%= form_for(@tweet) do |f| %>
  <% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% @tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :texto %><br>
    <%= f.text_field :texto %>
  </div>
  <div class="field">
    <%= f.label :usuario_id %><br>
    <%= collection_select :tweet,
                    :usuario_id,
                    Usuario.all,
                    :id,
                    :nome %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

feeter/app/views/tweets/_tweet.html.erb
<div style='width:500px'>
  <div style='width:100%'>
    <%= link_to tweet.usuario.nome, tweet.usuario %> feetou..
  </div>
  <div style='width:100%; padding-left:15px '>
    <%= tweet.texto %>
  </div>
  <div style='width:100%; text-align:right'>
    at <%= l tweet.created_at, :format => :short %>
  </div>
</div>

feeter/app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form' %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

feeter/app/views/tweets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tweets</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Texto</th>
      <th>Usuario</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tweets.each do |tweet| %>
      <tr>
        <td><%= tweet.texto %></td>
        <td><%= tweet.usuario.nome %></td>
        <td><%= link_to 'Show', tweet %></td>
        <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
        <td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tweet', new_tweet_path %>

feeter/app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form' %>

<%= link_to 'Back', tweets_path %>

feeter/app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Texto:</strong>
  <%= @tweet.texto %>
</p>

<p>
  <strong>Usuario:</strong>
  <%= @tweet.usuario.nome %>
</p>

<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>